name: "Test and Publish"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup node.js environment"
        uses: "actions/setup-node@v2"
        with:
          node-version: "14.x"
          registry-url: https://npm.pkg.github.com/
          scope: "@waytrade"
          always-auth: true

      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      - name: "Configure cache"
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-all-${{ hashFiles('**/yarn.lock') }}

      - name: "Install dependencies"
        run: yarn install

      - name: "Build App"
        run: yarn build

      - name: "Run Tests"
        run: sudo yarn test

      - name: "Bump Version"
        if: github.ref == 'refs/heads/master'
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: "v"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Upload Test-Report Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: test-report/
          retention-days: 5

      - name: "Deploy Test-Report"
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./test-report

      - name: "Upload Build Artifact"
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: dist-files
          retention-days: 1
          path: |
            dist/
            package.json

  publish:
    name: "Publish"
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: "Configure cache"
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-prod-${{ hashFiles('**/yarn.lock') }}

      - name: "Setup node.js environment"
        uses: "actions/setup-node@v2"
        with:
          node-version: "14.x"
          registry-url: https://npm.pkg.github.com/
          scope: "@waytrade"
          always-auth: true

      - name: "Download Build Artifact"
        uses: actions/download-artifact@v2
        with:
          name: dist-files

      - name: "Publish NPM Package"
        run: |
          echo registry=https://npm.pkg.github.com/waytrade >> .npmrc
          npm config set //npm.pkg.github.com//:_authToken=$NODE_AUTH_TOKEN
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
